# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIStruktur.ui'
#
# Created: Tue Apr 19 07:21:23 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 551))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tableView = QtGui.QTableView(self.gridLayoutWidget)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuTabelle = QtGui.QMenu(self.menubar)
        self.menuTabelle.setObjectName("menuTabelle")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtGui.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionCopy_CS = QtGui.QAction(MainWindow)
        self.actionCopy_CS.setObjectName("actionCopy_CS")
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionZeile_hinzuf_gen = QtGui.QAction(MainWindow)
        self.actionZeile_hinzuf_gen.setObjectName("actionZeile_hinzuf_gen")
        self.actionZeile_n_l_schen = QtGui.QAction(MainWindow)
        self.actionZeile_n_l_schen.setObjectName("actionZeile_n_l_schen")
        self.actionKopieren = QtGui.QAction(MainWindow)
        self.actionKopieren.setObjectName("actionKopieren")
        self.actionEinf_ge = QtGui.QAction(MainWindow)
        self.actionEinf_ge.setObjectName("actionEinf_ge")
        self.actionAusschneiden = QtGui.QAction(MainWindow)
        self.actionAusschneiden.setObjectName("actionAusschneiden")
        self.actionZeile_duplizieren = QtGui.QAction(MainWindow)
        self.actionZeile_duplizieren.setObjectName("actionZeile_duplizieren")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuEdit.addAction(self.actionKopieren)
        self.menuEdit.addAction(self.actionEinf_ge)
        self.menuEdit.addAction(self.actionAusschneiden)
        self.menuTabelle.addAction(self.actionZeile_hinzuf_gen)
        self.menuTabelle.addAction(self.actionZeile_n_l_schen)
        self.menuTabelle.addSeparator()
        self.menuTabelle.addAction(self.actionZeile_duplizieren)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuTabelle.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionClose, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Wahlanalyse Weinb 5BHIT", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "Datei", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Bearbeiten", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Hilfe", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTabelle.setTitle(QtGui.QApplication.translate("MainWindow", "Tabelle", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Öffnen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setStatusTip(QtGui.QApplication.translate("MainWindow", "Datei öffnen ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Speichern", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setToolTip(QtGui.QApplication.translate("MainWindow", "Datei speichern ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setStatusTip(QtGui.QApplication.translate("MainWindow", "Datei speichern ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_as.setText(QtGui.QApplication.translate("MainWindow", "Speichern unter", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_as.setToolTip(QtGui.QApplication.translate("MainWindow", "Datei speichern unter ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_as.setStatusTip(QtGui.QApplication.translate("MainWindow", "Datei speichern unter ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_as.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "Neu", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setStatusTip(QtGui.QApplication.translate("MainWindow", "Neue Datei anlegen ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy_CS.setText(QtGui.QApplication.translate("MainWindow", "Copy CS", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy_CS.setStatusTip(QtGui.QApplication.translate("MainWindow", "Copy CS ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("MainWindow", "Beenden", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setIconText(QtGui.QApplication.translate("MainWindow", "Beenden", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setToolTip(QtGui.QApplication.translate("MainWindow", "Programm beenden ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setStatusTip(QtGui.QApplication.translate("MainWindow", "Programm beenden ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZeile_hinzuf_gen.setText(QtGui.QApplication.translate("MainWindow", "Zeile hinzufügen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZeile_n_l_schen.setText(QtGui.QApplication.translate("MainWindow", "Zeile/-n löschen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKopieren.setText(QtGui.QApplication.translate("MainWindow", "Kopieren", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEinf_ge.setText(QtGui.QApplication.translate("MainWindow", "Einfügen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAusschneiden.setText(QtGui.QApplication.translate("MainWindow", "Ausschneiden", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZeile_duplizieren.setText(QtGui.QApplication.translate("MainWindow", "Zeile duplizieren", None, QtGui.QApplication.UnicodeUTF8))

