# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIStruktur.ui'
#
# Created: Tue Apr 19 09:14:03 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1284, 759)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tableView = QtGui.QTableView(self.centralwidget)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1284, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTabelle = QtGui.QMenu(self.menubar)
        self.menuTabelle.setObjectName("menuTabelle")
        self.menuBearbeiten = QtGui.QMenu(self.menubar)
        self.menuBearbeiten.setObjectName("menuBearbeiten")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtGui.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionCopy_CS = QtGui.QAction(MainWindow)
        self.actionCopy_CS.setObjectName("actionCopy_CS")
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionAddZeile = QtGui.QAction(MainWindow)
        self.actionAddZeile.setObjectName("actionAddZeile")
        self.actionDelZeile = QtGui.QAction(MainWindow)
        self.actionDelZeile.setObjectName("actionDelZeile")
        self.actionKopieren = QtGui.QAction(MainWindow)
        self.actionKopieren.setObjectName("actionKopieren")
        self.actionEinf = QtGui.QAction(MainWindow)
        self.actionEinf.setObjectName("actionEinf")
        self.actionAusschneiden = QtGui.QAction(MainWindow)
        self.actionAusschneiden.setObjectName("actionAusschneiden")
        self.actionDuplZeile = QtGui.QAction(MainWindow)
        self.actionDuplZeile.setObjectName("actionDuplZeile")
        self.actionKopieren_2 = QtGui.QAction(MainWindow)
        self.actionKopieren_2.setObjectName("actionKopieren_2")
        self.actionEinf_gen = QtGui.QAction(MainWindow)
        self.actionEinf_gen.setObjectName("actionEinf_gen")
        self.actionAusschneiden_2 = QtGui.QAction(MainWindow)
        self.actionAusschneiden_2.setObjectName("actionAusschneiden_2")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuTabelle.addAction(self.actionAddZeile)
        self.menuTabelle.addAction(self.actionDelZeile)
        self.menuTabelle.addSeparator()
        self.menuTabelle.addAction(self.actionDuplZeile)
        self.menuBearbeiten.addAction(self.actionKopieren_2)
        self.menuBearbeiten.addAction(self.actionEinf_gen)
        self.menuBearbeiten.addAction(self.actionAusschneiden_2)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTabelle.menuAction())
        self.menubar.addAction(self.menuBearbeiten.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionClose, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Wahlanalyse Weinb 5BHIT", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "Datei", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTabelle.setTitle(QtGui.QApplication.translate("MainWindow", "Tabelle", None, QtGui.QApplication.UnicodeUTF8))
        self.menuBearbeiten.setTitle(QtGui.QApplication.translate("MainWindow", "Bearbeiten", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Öffnen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setStatusTip(QtGui.QApplication.translate("MainWindow", "Datei öffnen ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Speichern", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setToolTip(QtGui.QApplication.translate("MainWindow", "Datei speichern ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setStatusTip(QtGui.QApplication.translate("MainWindow", "Datei speichern ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_as.setText(QtGui.QApplication.translate("MainWindow", "Speichern unter", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_as.setToolTip(QtGui.QApplication.translate("MainWindow", "Datei speichern unter ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_as.setStatusTip(QtGui.QApplication.translate("MainWindow", "Datei speichern unter ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_as.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "Neu", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setStatusTip(QtGui.QApplication.translate("MainWindow", "Neue Datei anlegen ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy_CS.setText(QtGui.QApplication.translate("MainWindow", "Copy CS", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy_CS.setStatusTip(QtGui.QApplication.translate("MainWindow", "Copy CS ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("MainWindow", "Beenden", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setIconText(QtGui.QApplication.translate("MainWindow", "Beenden", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setToolTip(QtGui.QApplication.translate("MainWindow", "Programm beenden ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setStatusTip(QtGui.QApplication.translate("MainWindow", "Programm beenden ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddZeile.setText(QtGui.QApplication.translate("MainWindow", "Zeile hinzufügen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddZeile.setStatusTip(QtGui.QApplication.translate("MainWindow", "Hinzufügen einer neuen Zeile zur Tabelle ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddZeile.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Hinzufügen einer neuen Zeile zur Tabelle ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddZeile.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelZeile.setText(QtGui.QApplication.translate("MainWindow", "Zeile löschen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelZeile.setStatusTip(QtGui.QApplication.translate("MainWindow", "Löschen einer Zeile der Tabelle...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelZeile.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Löschen einer Zeile der Tabelle...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelZeile.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+X", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKopieren.setText(QtGui.QApplication.translate("MainWindow", "Kopieren", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEinf.setText(QtGui.QApplication.translate("MainWindow", "Einfügen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAusschneiden.setText(QtGui.QApplication.translate("MainWindow", "Ausschneiden", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDuplZeile.setText(QtGui.QApplication.translate("MainWindow", "Zeile duplizieren", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDuplZeile.setStatusTip(QtGui.QApplication.translate("MainWindow", "Duplizieren einer Zeile der Tabelle ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDuplZeile.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Duplizieren einer Zeile der Tabelle ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDuplZeile.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKopieren_2.setText(QtGui.QApplication.translate("MainWindow", "Kopieren", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKopieren_2.setStatusTip(QtGui.QApplication.translate("MainWindow", "Kopieren ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKopieren_2.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Kopieren ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKopieren_2.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEinf_gen.setText(QtGui.QApplication.translate("MainWindow", "Einfügen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEinf_gen.setStatusTip(QtGui.QApplication.translate("MainWindow", "Einfügen ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEinf_gen.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Einfügen ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEinf_gen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+V", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAusschneiden_2.setText(QtGui.QApplication.translate("MainWindow", "Ausschneiden", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAusschneiden_2.setStatusTip(QtGui.QApplication.translate("MainWindow", "Ausschneiden...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAusschneiden_2.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Ausschneiden...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAusschneiden_2.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+X", None, QtGui.QApplication.UnicodeUTF8))

